repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
        args:
        - -m
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
    -   id: trailing-whitespace
