repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .(docker|git)ignore
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace

# rst
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.3
    hooks:
    -   id: rst-backticks
-   repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.0
    hooks:
    -   id: rst-linter

# terraform
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.21.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
