version: '2'

services:
  nginx:
    build: nginx/
    image: thekevjames/infrastructure-nginx
    hostname: nginx
    network_mode: host
    ports:
      - "80:80"
    volumes:
      - ./webroot:/usr/share/nginx/volume
