version: '2'

services:
  consul:
    build: consul/
    hostname: consul
    network_mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  nginx:
    build: nginx/
    hostname: nginx
    network_mode: host
    ports:
      - "80:80"
