version: 2.1

orbs:
  linter: thekevjames/linter@1

jobs:
  lint:
    docker:
      - image: hashicorp/terraform:0.15.0
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - run:
          name: install python
          command: |
            apk add -U bash python3
            python3 -m ensurepip
            ln -s /usr/bin/python3 /usr/bin/python
      - checkout
      - run: terraform init
      - linter/pre-commit

  terraform:
    docker:
      - image: hashicorp/terraform:0.15.0
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve

workflows:
  run-jobs:
    jobs:
      - lint
      - terraform:
          filters:
            branches:
              only: master
          requires:
            - lint
