version: 2.1

orbs:
  linter: talkiq/linter@2

jobs:
  lint:
    docker:
      - image: hashicorp/terraform:1.2.1
    steps:
      - run: apk add -U bash gcc musl-dev python3 python3-dev py3-yaml
      - run: python3 -m ensurepip
      - run: ln -s /usr/bin/python3 /usr/bin/python
      - checkout
      - linter/pre-commit

  terraform-plan:
    docker:
      - image: hashicorp/terraform:1.2.1
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - checkout
      - run: terraform init
      - run: terraform plan -lock=false

  terraform-apply:
    docker:
      - image: hashicorp/terraform:1.2.1
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve

workflows:
  run-jobs:
    jobs:
      - lint
      - terraform-plan:
          filters:
            branches:
              ignore: master
          requires:
            - lint
      - terraform-apply:
          filters:
            branches:
              only: master
          requires:
            - lint
