version: 2

jobs:
  lint:
    docker:
      - image: python:3.6.4
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - run:
          name: install terraform
          command: |
            apt-get update
            apt-get install -y unzip
            curl -o /terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
            unzip /terraform.zip -d /usr/local/bin
            chmod a+x /usr/local/bin/terraform
      - checkout
      - run: pip install pre-commit
      - run: terraform init
      - run: pre-commit run --all-files

  terraform:
    docker:
      - image: hashicorp/terraform:0.11.7
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve

workflows:
  version: 2
  run-jobs:
    jobs:
      - lint
      - terraform:
          filters:
            branches:
              only: master
          requires:
            - lint
