version: 2.1

orbs:
  linter: talkiq/linter@dev:7bb6c1a

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.6.5
    # https://circleci.com/docs/env-vars#alpine-linux
    shell: /bin/sh -leo pipefail
    environment:
      BASH_ENV: /etc/profile

jobs:
  terraform-plan:
    executor: terraform
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - checkout
      - run: terraform init
      - run: terraform plan -lock=false

  terraform-apply:
    executor: terraform
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          executor: terraform
          pre-steps:
            - run: apk add -U bash python3
      - terraform-plan:
          filters:
            branches:
              ignore: master
          requires:
            - linter/pre-commit
      - terraform-apply:
          filters:
            branches:
              only: master
          requires:
            - linter/pre-commit
