version: 2

jobs:
  check:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install pre-commit
      - run: pre-commit run --all-files

  nginx:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t nginx nginx/
      - deploy:
          name: login to dockerhub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - deploy:
          name: push image (hash)
          command: |
            docker tag web "thekevjames/nginx:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}"
            docker push "thekevjames/nginx:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}"
      - deploy:
          name: push image (branch)
          command: |
            docker tag web "thekevjames/nginx:${CIRCLE_BRANCH}"
            docker push "thekevjames/nginx:${CIRCLE_BRANCH}"
      - deploy:
          name: push image (latest)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag web thekevjames/nginx:latest
              docker push thekevjames/nginx:latest
            fi

  ssl:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t ssl ssl/
      - deploy:
          name: login to dockerhub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - deploy:
          name: push image (hash)
          command: |
            docker tag web "thekevjames/ssl:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}"
            docker push "thekevjames/ssl:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}"
      - deploy:
          name: push image (branch)
          command: |
            docker tag web "thekevjames/ssl:${CIRCLE_BRANCH}"
            docker push "thekevjames/ssl:${CIRCLE_BRANCH}"
      - deploy:
          name: push image (latest)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag web thekevjames/ssl:latest
              docker push thekevjames/ssl:latest
            fi

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - deploy:
          name: deploy images
          command: |
            ssh -oStrictHostKeyChecking=no ubuntu@thekev.in "
              docker service update --image "thekevjames/nginx:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}" thekevjames_nginx
              docker service update --image "thekevjames/ssl:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:8}" thekevjames_ssl
            "

workflows:
  version: 2
  check-build-and-deploy:
    jobs:
      - check

      - nginx:
          context: org-global
          requires:
            - check

      - ssl:
          context: org-global
          requires:
            - check

      - deploy:
          requires:
            - nginx
            - ssl
          filters:
            branches:
              only: master
