version: 2

jobs:
  check:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install pre-commit

      - run:
          name: run pre-build tests
          command: |
            pre-commit run --all-files

  build-nginx:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: build image
          command: |
            docker build -t nginx nginx/
            docker tag nginx "thekevjames/nginx:${CIRCLE_SHA1}"
            docker tag nginx "thekevjames/nginx:latest"

  push-nginx:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - deploy:
          name: push image
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

            docker push "thekevjames/nginx:${CIRCLE_SHA1}"
            docker push "thekevjames/nginx:latest"

  build-ssl:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: build image
          command: |
            docker build -t ssl ssl/
            docker tag ssl "thekevjames/ssl:${CIRCLE_SHA1}"
            docker tag ssl "thekevjames/ssl:latest"

  push-nginx:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - deploy:
          name: push image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

              docker push "thekevjames/ssl:${CIRCLE_SHA1}"
              docker push "thekevjames/ssl:latest"
            fi

  deploy:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - deploy:
          name: deploy images
          command: |
            ssh -oStrictHostKeyChecking=no ubuntu@thekev.in "
              docker service update --image thekevjames/nginx:latest thekevjames_nginx
              docker service update --image thekevjames/ssl:latest thekevjames_ssl
            "

workflows:
  version: 2
  check-build-and-deploy:
    jobs:
      - check
      - build-nginx:
          requires:
            - check
      - push-nginx:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - build-nginx
      - build-ssl:
          requires:
            - check
      - push-ssl:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - build-ssl
      - deploy:
          requires:
            - push-nginx
            - push-ssl
          filters:
            branches:
              only: master
