version: 2.1

orbs:
  linter: talkiq/linter@4.0.0

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.13.4
    # https://circleci.com/docs/env-vars#alpine-linux
    shell: /bin/sh -leo pipefail
    environment:
      BASH_ENV: /etc/profile
      GOOGLE_APPLICATION_CREDENTIALS: /key.json

jobs:
  terraform-plan:
    executor: terraform
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - checkout
      - run: terraform init
      - run: terraform plan -lock=false

  terraform-apply:
    executor: terraform
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - checkout
      - run: terraform init
      - run: terraform plan -out=/tmp/plan.out
      - run: terraform apply -auto-approve /tmp/plan.out
      - store_artifacts:
          path: /tmp/plan.out

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          executor: terraform
          pre-steps:
            - run: apk add -U bash python3
            # When this fails, see .github/renovate.json5
            - run: python3 --version | grep 3.12
      - terraform-plan:
          filters:
            branches:
              ignore: master
          requires:
            - linter/pre-commit
      - terraform-apply:
          filters:
            branches:
              only: master
          requires:
            - linter/pre-commit
