#!/bin/sh
letsencrypt certonly --webroot -w /etc/letsencrypt/webroot \
    -d thekev.in -d www.thekev.in \
    -d devstat.thekev.in -d api.devstat.thekev.in \
    -d jarvis.thekev.in \
    -d league.thekev.in \
    -d netdata.thekev.in -d status.thekev.in \
    -d youshouldread.thekev.in -d ysr.thekev.in
